### ISSUE TITLE
Investigate and possibly replace custom redux bindings with react-redux

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1000]
I just noticed today that we aren't actually using `react-redux` but instead of some custom code to bind react and redux state. We should probably use the real bindings. 

Need to investigate why this was done and what the level-of-effort would be do use `react-redux`. My intuition is that it was done because of our use of `react-router`, which may have made using `react-redux` complicated/hard at the time. There are docs on how to do this now: http://redux.js.org/docs/advanced/UsageWithReactRouter.html

Likely benefits of using react-redux:
- Easier to use other third-party modules that assume `react-redux`
- Less of our own code to maintain and document
- Better understanding by devs due to consistency with other react+redux projects
- We'd get rid of all the `actionCreators`, which will reduce our custom code

**Comment by jseppi** [comment]
It looks like we will be able to do the conversion piecemeal, which is nice. For instance, I'm able to wrap our custom `<Provider>` with the react-redux Provider (named below `<ReactReduxProvider>`):

```js
store.subscribe(() => {
  render((
    <ReactReduxProvider store={store}>
      <Provider state={{ get: store.getState }}>
        <Router history={browserHistory}>
          {routes}
        </Router>
      </Provider>
    </ReactReduxProvider>
  ), mainEl);
});
```

and I think I'll be able to use react-redux to connect components one-by-one.

**Comment by jmhooper** [comment]
Discussed this with @jseppi this morning and we both agree that the initial work to remove the custom provider and use the `react-redux` provider is pretty trivial and that the custom provider can be removed piecemeal. 

Using the `react-redux` provider lets us pull in modules for things like notifications or logging from the community (saving us from writing custom code in the future). Also there's the advantage of removing code from our codebase that we'd otherwise have to maintain.
