### ISSUE TITLE
Build Log page can display logs for incorrect site

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1012]
If the URL is manually edited, the Build Log page can be made to show the logs of a build not related to the current site that is displayed. This is not a security issue as it can only do this for build logs of repositories that the auth'd user has access to.

For example:
This URL `https://federalist-staging.18f.gov/sites/49/builds/2074/logs` is for site id `49`, which is `jseppi/digital.gov-hugo`, but the logs with id `2074` are for `18f/doi-extractives-data`:

<img width="1157" alt="screen shot 2017-06-16 at 10 14 31 am" src="https://user-images.githubusercontent.com/697848/27232691-9efb2876-527c-11e7-87db-b1871bd6d893.png">

The build-log api response contains the site id with which the logs are associated, so a possible fix is to make sure that that site id matches the site id in the SiteContainer. If not, then either show an error or redirect the URL to the proper site id route (ie, the one associated with the current log).

**Comment by jmhooper** [comment]
Interesting, good catch.

I'm not sure we want to push the handling for this off onto the frontend. The API should know not to render builds under the wrong site.

It would be nice to move to shallow resources for these sorts of things. So, `/site/:id/build` for builds associated with the site, then `/build/:id` to the build instead of `/site/:isite_d/build/:id`. From the backend's perspective, the site ID is superfluous since it has no bearing on how the request is processed and is just another thing for it to verify.

The issue with that format is that unfortunately the frontend depends on the site id being present in the URL to know which site to display in the parent site container.

**Comment by jseppi** [comment]
The API doesn't get the site id in the build log request. It only gets the build id, for example: http://localhost:1337/v0/build/1932/log.

Using shallow URLs is not a bad idea either, but will require re-jiggering of the React router.

**Comment by jseppi** [comment]
Oh, which you noted, but I didn't get to the end of your comment before commenting :P

**Comment by wslack** [comment]
Is this really a bug though? I like that URLs show both the build ID and the site ID. Manually editing them seems like a side-case that won't challenge users.

Is the concern just that the URL (if edited) is misleading?

**Comment by jseppi** [comment]
The UI also is misleading because it shows the header for a site different from what the rest of the page is displaying.

It's certainly a side case, but still seems "wrong" for it to be possible.

**Comment by wslack** [comment]
Iceboxed!

**Comment by wslack** [comment]
Closing as there's no security risk. There's a wonky UX when people change their URL but they shouldn't do that.
