### ISSUE TITLE
File names that being with ~ (tilde) cause builds to break

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1065]
Example: https://github.com/GSA/fedramp-tailored/pull/146#issuecomment-314906660

**Comment by jmhooper** [comment]
I don't know that this is an issue with our build container, so much as it is an issue with Jekyll. The same thing fails locally.

I looked and the Jekyll team has addressed this: https://github.com/jekyll/jekyll/issues/4457

The FedRamp Tailored team is seeing the issue because they are still on Jekyll 2.5

**Comment by jseppi** [comment]
ha, excellent! closing :)
