### ISSUE TITLE
Simplify actions/actionCreators

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1082]
Once we've transitioned to `react-redux` (#1005)  we should be able to simplify all of our redux actions.

We might want to consider [`redux-thunk`](https://github.com/gaearon/redux-thunk)

This article looks like a helpful guide: https://codepen.io/stowball/post/a-dummy-s-guide-to-redux-and-thunk-in-react

**Comment by el-mapache** [comment]
@jseppi Can you go into a little more depth on how `redux-thunk` makes out code simpler? I've read a few posts etc about it but its not super clear to me what the improvement is.

I seems like thunk can be really useful when you have a lot of complex action logic in your components, but we pretty much handle all of that in our actions and let the components display the new data.

I've read the article you linked in the issue, but in that article the author never actually does anything with the fact that an action can now return a promise, and I'm also not quite clear on how we would use this functionality in our current app, or how this makes the code simpler.

Since you are rolling off soon I was hoping to learn a little more about this. Thanks!

**Comment by jseppi** [comment]
I have nearly no recollection of what I was thinking with regards to `redux-thunk` when I created this :\ 

I think my main thinking at the time was the I didn't really like the separation of actions and actionCreators into separate files with (to me anyway) somewhat confusing names and import renaming (eg, we have a lot of this pattern: `import someAction as createSomeAction from ./actionCreators/someAction`)

Happy to close this out if you think the organization is fine as it is.

**Comment by el-mapache** [comment]
Ha no worries!

I I do think that the naming conventions are confusing, but I don't necessarily think that the separation between action creators and the actions themselves are inherently bad.

It does make testing the actions easier since we can test the business logic without also needing to validate that the actions are dispatching a properly formatted object
