### ISSUE TITLE
Design issue when the branch name is a very long string

### ISSUE THREAD

**Issue by sp1d3r** [18F/federalist#1147]
Hello. I noticed small design issue - when the branch name is too long, it can break the page design:

![zxzx](https://user-images.githubusercontent.com/24297694/30112879-826e5d74-931b-11e7-9c2c-a1d500b88844.PNG)

The possible CSS fix can be `word-break` or `overflow:hidden` parameters.

**Comment by jseppi** [comment]
Thanks for letting us know, @sp1d3r!

**Comment by wslack** [comment]
There's a lot of front end stuff we still want to do! I've triaged this issue.

**Comment by jseppi** [comment]
Maybe use [`text-overflow: ellipsis;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)

**Comment by sp1d3r** [comment]
Sounds nice! In the meantime i discovered two more issues with same root cause:
1) When the string in the error message is too long
![12](https://user-images.githubusercontent.com/24297694/30164145-3d395bcc-93e4-11e7-9841-9e09799ad037.PNG)
2) When the repository name is too long (GitHub allows repository names up to 100 chars, and i used 100 chars for the test)
![123](https://user-images.githubusercontent.com/24297694/30164146-3d3e7684-93e4-11e7-9029-cd340a570eba.PNG)

**Comment by jseppi** [comment]
Thanks for finding and documenting those!

**Comment by wslack** [comment]
If you had seen how the app used to be in this area....it was much worse in beta. But can still be better!

**Comment by el-mapache** [comment]
@wslack I think this issue is good to close after the work that @line47 did to better integrate USWDS a while back.

Here are a couple screen shots of problem areas that no longer overflow weirdly:

<img width="856" alt="screen shot 2018-03-26 at 2 26 38 pm" src="https://user-images.githubusercontent.com/1421848/37925166-e9cc7634-3101-11e8-9f67-10cbe5bdead9.png">


<img width="828" alt="screen shot 2018-03-26 at 2 28 19 pm" src="https://user-images.githubusercontent.com/1421848/37925188-f8f30466-3101-11e8-8606-7eb0f9825f6f.png">

**Comment by sp1d3r** [comment]
Looks cool:) Issue is not reproducible anymore.
