### ISSUE TITLE
Remove no-case dependency

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1153]
(takes care of a possible regex bug)

**Comment by jseppi** [comment]
Hrm, we don't directly depend on `no-case` -- it's a few down our dependency tree. `html-loader` is the ancestor dependency that we actually have in our `package.json`.

```
$ yarn why no-case
yarn why v0.27.5
[1/4] Why do we have the module "no-case"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
info This module exists because "html-loader#html-minifier#camel-case" depends on it.
info Disk size without dependencies: "56kB"
info Disk size with unique dependencies: "76kB"
info Disk size with transitive dependencies: "76kB"
info Number of shared dependencies: 1
```

**Comment by jseppi** [comment]
As I mentioned in Slack, no user input was ever going through `no-case`. It was included because of `html-loader`, which was used in our webpack config to bundle html snippets. We don't actually have any html snippets in our bundle any more since the changes from PR #1120.

I'll remove `html-loader` loader since we aren't using it, but the regex issue in `no-case` would not have affected our application.

**Comment by wslack** [comment]
@jseppi changed issue title accordingly; sgtm as per Slack
