### ISSUE TITLE
Add a way to keep Federalist sites behind basic auth

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1253]
We've had a number of questions about whether we can put a site behind HTTP basic auth. This is a feature request we get frequently enough to warrant some thought on it.

**Comment by jseppi** [comment]
I think @wslack has mentioned this before, but I'm wondering how this would impact an ATO. Once you add auth like this, that means you also need stuff like user management, user auditing, etc, right? Or can we get around that by just specifying that "this auth isn't really for anything other than to keep prying eyes slightly off of it, but if they do get in, no worries because it's all public."

**Comment by wslack** [comment]
Yeah - I don't think this auth means anything besides "you can set a password that's required to view the site" - nothing fancy, everything is still considered public. It's more about comfort than real security.

**Comment by wslack** [comment]
The request I got this week was for PIV/CAC verification, which is a whole other level.

**Comment by wslack** [comment]
I think this should be tied into an epic around setting up a way for Federalist to publish behind auth. cc @jseppi for thoughts.

**Comment by jseppi** [comment]
Not totally fleshed out, but I think the basics of how auth would work:

1) create a new non-public, non-website-enabled s3 bucket to host protected site content
1) create a new proxy app that has the AWS keys to that bucket
1) store per-protected-site auth credentials in database
1) use basic auth on new proxy app to auth, proxy app then proxies requests to new s3 bucket to serve content

**Comment by wslack** [comment]
That sounds right to me. We would also not provide any promises re security.

**Comment by amirbey** [comment]
duplicate issue ... currently tracked in #2408
