### ISSUE TITLE
Update flexbox for template selection 

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1298]
After https://github.com/18F/federalist/pull/1295 is merged, we should modify the line in `TemplateSiteList/index.js` that says

```jsx
<div className="flexbox-grid flexbox-grid-4" key={row}>
```

to 

```jsx
<div className={`flexbox-grid flexbox-grid-${MAX_CELLS_PER_ROW}`} key={row}>
```

and add a few more `.flexbox-grid-#` classes in `_flexbox.scss` to handle different numbers of items in a row. I'm thinking `3` and `5` would be enough.

Also take a look at how the template selection Flexbox works at responsive sizes. 

ref discussion: https://github.com/18F/federalist/pull/1295/files#r152284690

**Comment by line47** [comment]
**How do we want the flexbox to behave at certain screen sizes?** 
Currently each template card is set to a specific width and when the browser gets below that width it drops to the next line.

### Here are a few screenshots
<img width="784" alt="screen shot 2017-12-04 at 1 00 00 pm" src="https://user-images.githubusercontent.com/1449852/33567843-81d31590-d8f2-11e7-83de-5d4b12a04c0b.png">
<img width="560" alt="screen shot 2017-12-04 at 1 00 10 pm" src="https://user-images.githubusercontent.com/1449852/33567845-843eaf74-d8f2-11e7-9fee-5956d504a675.png">

CC @wslack

**Comment by wslack** [comment]
@line47 I would rather it behave like it used to and not use a specific width, but instead vary depending on screen width.

**Comment by wslack** [comment]
Is that possible? Why did we lose that behavior?

**Comment by line47** [comment]
👇 If we go back to percentages this type of thing happens which isn't a very good UI as the text wraps so much.
<img width="615" alt="screen shot 2017-12-04 at 1 21 18 pm" src="https://user-images.githubusercontent.com/1449852/33569407-965fb6a8-d8f7-11e7-9079-738c1a19c7e2.png">

In this type of layout it would be better if the designs were 2 up instead of 4.

I was thinking we could do the following:
- 1 up at small screens
- 2 up at medium screens
- 4 up at large screens

**Comment by wslack** [comment]
The previous layout jumped to those widths as you specified - so it never looked like that. I agree that it should switch to a 2x2 grid when thinner.
