### ISSUE TITLE
Move Federalist docs site into Federalist site and move Federalist application to /app/ URL

### ISSUE THREAD

**Issue by line47** [18F/federalist#1333]
Place the Federalist application at  `federalist.18f.gov/app/` and have the the docs/informational site (including the homepage) a Jekyll Federalist site and have everything live at federalist.18f.gov. 
This option is doable from a technical standpoint. 

To accomplish this It would need an adjustment to the federalist-proxy or need its own reverse proxy server. The proxy would have to match requests for `federalist.18f.gov/app/` and reverse proxy them to wherever the app is hosted (like  to `federalist-prod.app.cloud.gov`)

- [ ] Federalist docs site would be consumed under the main Federalist site
- [ ] Federalist homepage would be part of the Jekyll site
- [ ] Federalist application can be accessed via `/app/` or something similar in the URL string
- [ ] Host the Federalist site on Federalist 🐶 

CC @wslack @jseppi

**Comment by wslack** [comment]
What if we put the Federalist app at federalist-config.18f.gov and moved the docs site onto the main URL while keeping the "login" button pointed at the new domain?

@el-mapache how long do you think that would take? It'd be best to do it before the new ATO (so this sprint or next sprint).

**Comment by jseppi** [comment]
That's a good idea, @wslack. It'll mostly be ops tasks, like changing the Federalist OAuth app to use the new URL for the auth callback, etc. We might run into problems with existing webhooks though. I'm not super caught up on how that all works so I don't know for sure right now.

**Comment by el-mapache** [comment]
@wslack Doesn't the current splash page rely on server side variables to display error messages? I'm not sure if its totally worth rewriting one page as a jekyll app. 

I also think the `federalist-config` url is slightly awkward, especially to the mostly non-technical users who are interacting with the site.

**Comment by jseppi** [comment]
Fair point, @el-mapache. The dynamic content on the front page will indeed need to be removed or would require additional changes to make work (like AJAXing in the number of builds from the app).

I think the login errors could be moved to another view in the app, but it's additional development work.

The "Site Wide Error" messaging could probably be removed and done just in the new jekyll site, which might actually make it easier.

**Comment by wslack** [comment]
(we could move the app, but that would mean having to write a script to edit/redo all of the webhooks in all Federalist repos, which could go wrong in many many ways)

**Comment by jseppi** [comment]
There's also the reverse proxy option, which I think would basically be:

1. Host all static federalist content, built with federalist itself, at https://federalist-content.app.cloud.gov (or wherever)
1. Host federalist app at https://federalist-app.app.cloud.gov (or wherever)
1. Setup a separate nginx reverse proxy (ie, not federalist-proxy) to serve requests to `/app/` from federalist-app, and serverall other requests from federalist-content.
1. Point the CloudFront distro for https://federalist.18f.gov at this reverse proxy server.

**Comment by el-mapache** [comment]
It seems to me the steps we need to take are:

* Create a new repo (in the federalist org?) with a skeleton jekyll app
* Move the static content in the current app into that repo
* host this on federalist at a dummy URL for now
* I think we need to host a `-staging` version as well, since the login button is now going to have to conditionally link to either `federalist-app` or `federalist-staging-app`
* Add an API route for getting the `build counter` information
* Add a little bit of JS to the static site to pull that build information
* Move `federalist-staging` to `federalist-app-staging`, and update all the routes that point to it (I guess webhooks and the OAuth app in GitHub?)
* Add  a landing page to the site at `federalist-app` in case github login fails. This could be part of the React app or another `.njs` page. It would probably need to display the login error and maybe have a redirect back to the docs site?
* Move the current app to `federalist-app{-staging}.18f.gov`

The most onerous part of this is going to be updating the webhooks, I think everyone with a repo on Federalist is going to have to update those repos to point to our new URL.

There will probably also be a bit of downtime when we point the app over to the new URL, but that seems like less of a big deal since we can alert customers and do it in the evening.

@jseppi Can you sanity check this whenever you get a chance?

**Comment by el-mapache** [comment]
The reverse proxy makes this easier for sure!

**Comment by wslack** [comment]
@el-mapache is the juice worth the squeeze, though? That seems like a lot of work compared to simply enabling us to put a few other static pages on federalist.18f.gov.

**Comment by jseppi** [comment]
I agree with your juice squeezing metaphor 🍊 

If we're only going to have a few additional content pages, then I think what I'm doing for #1337 will suffice. I suppose an argument could be made that it would be nice for us to dogfood the platform for this use case, but we already dogfood it quite and bit and this usecase wouldn't really be easy for our partners to replicate.

**Comment by el-mapache** [comment]
Yes, I think adding additional static pages is fine for now. This seems like a bit too much effort for what we need at the moment.

**Comment by wslack** [comment]
If @line47 agrees we can close this out.
