### ISSUE TITLE
strategy and priorities for Federalist program

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#1399]
Hey - Can you write a list of the top priorities and goals for the Federalist program? I'm especially interested in the priorities/goals that influence issue prioritization.

**Comment by wslack** [comment]
@leahbannon absolutely!

Federalist follows a Weighted Shortest Job First (WSJF) prioritization model, with three variables:

- How important is the feature to users or for enabling a sale - aka business value
- How urgent is the issue - aka time criticality
- How much does the issue enable the team to deliver on business value - aka Risk reduction-opportunity enablement value

Those are combined then divided by the level of effort of the work for a "bang for the buck" metric. Generally, we will bias towards smaller efforts with high impact, but sometimes we do **huge projects** if the need is great - like rewriting the entire backend to use a different library.

The priorities right now for the program are:

1. Get the next ATO. We don't have clear requirements for this yet, but the "remove a user" functionality Adam is making and the SSP David is working on fit under this.
2. Get more sales. That means working on the website front-end and showcasing better what Federalist can do, ideally to enable more scalable sales.
 -- A subpart of this is making the backend of Federalist more powerful and able to handle edge cases.
3. Conduct some overdue UX/content research.
4. Improve documentation so that support is more self-service. That is typically me copying support answers into our docs website, which is low impact but also low effort.

A separate project is supporting OPP's completion of its transition to Federalist.

**Comment by leahbannon** [comment]
Awesome, thank you. As discussed, can you list the product-related priorities?

**Comment by wslack** [comment]
My next task: 

Complete the list of priorities with product priorities.

**Comment by wslack** [comment]
After that: label each issue in In-Progress and PR1 with the appropriate label.

**Comment by wslack** [comment]
Priorities:
1. Ensure Federalist is up and users are not derailed by bugs that block them from their work.
   - Maintain the Federalist ATO, leveraging cloud.gov as much as possible

2. Increase sales
   - Ensure that the Federalist demo presents well
   - Create and iterate materials for sales (homepage, videos, documents, slidedecks)

3. Make Federalist (whether out of auth, in auth, or interacting on Github)
   - convey professionalism (so that we are trusted)
   - easy to use, especially via self-service documentation
       - Conduct user research and analysis

4. Improve templating
     - Enable cost savings for Federalist customers by getting them closer to a completed site from the start, mining existing work as much as possible for code and inspiration. (more detail in the [templates document](https://docs.google.com/document/d/1HfJmjbQ7uFh7z0tB6T0d2RiIg5vLYTvTl0bnZFzHPvs/edit)).    - Make it easy for users to add useful functions to existing sites

5. Improve Federalist backend functionality
    - Allow technical users to quickly grasp how the system works and run locally
    - Some changes may be needed for the ATO

**Comment by wslack** [comment]
Next step: Leah to review

**Comment by leahbannon** [comment]
Excellent. :)

Some thoughts:
1. I won’t be concerned if you don’t like the rearranging and changing — I’m more interested to see what you think.
1. I added user stories, which really helped me think through this.
1. I'm glad it was there, but I removed usability testing. 😱  Lately I’ve been thinking we shouldn’t include 18F core values in our priorities, they're just mandatory (e.g., you wouldn't include maintain open source on here, either). As usability testing is conducted regularly, findings should be rated (by the designer and PM together or at backlog grooming) based on the severity of the issue AND the overall program priorities below. 
Ratings:
UX1 - Cosmetic issue: no need to fix unless extra time is available on project
UX2 - Minor usability problem, does not affect a high priority: fixing this should be given low priority
UX3 - Major usability problem, affects a high priority: important to fix, so should be given high priority
UX4 - Usability catastrophe: imperative to fix, this is blocking use of a required feature


Priorities:

1. Ensure Federalist is up and working (metric: maintain x% up time?) and maintain the Federalist ATO (metric: binary), leveraging cloud.gov as much as possible. (As a SaaS, in order to survive, I need to reliably work for my customers and maintain required security/compliance.)
1. Increase sales. (As a government program, in order to survive, I need to continue to demonstrate value and/or maintain cost recoverability.) This includes:
* Ensure that the Federalist demo presents well
* Ensure marketing/demo materials are helping make sales (e.g., homepage, videos, documents, slide decks)
1. Keep/make current customers happy (metric: maintain >85%? retention rate - currently 100%!!). (As a government program, in order to survive, I need to continue to demonstrate value and/or maintain cost recoverability.) This includes:
* Convey professionalism (so that we are trusted)
* Improve templating (As a Federalist user, in order to realize a major benefit of Federalist over other options by saving time/costs/resources, I need to find a template that works for me and quickly launch my new site.) (Note: mine existing work as much as possible for code and inspiration. (more detail in the templates document
* Make it easy for users to add useful functions to existing sites (Does this refer to open source dev contributions?)
* Improve Federalist backend functionality (As a developer Federalist user, in order to enjoy using Federalist, I need to quickly grasp how the system works and run locally.)

Let's discuss after stand up tomorrow?

**Comment by leahbannon** [comment]
After discussing with Will, I'm creating an internal project README to paste this into. I think we might have more work to do to make sure the sub-bullets under 2 and 3 are more comprehensive, but I think this is sufficient to close out the issue.
