### ISSUE TITLE
Remove redux-logger from production bundle (set logging to happen local-only)

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1481]
It's not necessary there, and just adds weight to the bundle.

- Level of Effort: low
- Definition of Done: redux-logger is no longer in the production bundle

Only errors should get logged in PROD.

**Comment by wslack** [comment]
Did we just use this yesterday to investigate something, or was that something else?

**Comment by wslack** [comment]
What's the positive impact of doing this?

**Comment by jseppi** [comment]
Yup, it sorta came in handy while looking at #1484 (though we still haven't totally figured out the root cause of that issue).

**Comment by jseppi** [comment]
I think the only positive impact is a slight reduction in bundle size (`3.4KB` gzipped). Not really worth losing the potential utility, IMO. What do you think @el-mapache?

**Comment by el-mapache** [comment]
@jseppi I'm fine to leave it in then, I opened this thinking you could just remove it as part of the package cleanup you were doing at the beginning of the year.

@wslack the positive impact of doing this is that the JS bundle size is smaller, as James pointed out, and that the console doesn't have a bunch of logging, which I think is sort of sloppy in a production app. Theoretically the logging could slow down the site in production as well, since writes to the system out are expensive. In practice this isn't a huge deal, since we aren't running animations of loops with a lot of logic in them that also produce these logs.

Ultimately, I thought since we were cleaning up unused code from our production JS bundle, we might as well go all the way.

**Comment by wslack** [comment]
> At this point, since we are using the logging to troubleshoot, and it's well past the date of the work James did, we can just close this issue.

Makes sense but I'm going to icebox since it may make sese later. TY for opening it!

**Comment by wslack** [comment]
Ideally, we would support more local logging and not doing this in production. This is a best practice violation.
