### ISSUE TITLE
When setting Federalist up locally, variable names are confusing

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1516]
- Level of Effort: Low
- Implementation Sketch (if higher than a "low" effort):
  - Write a script that devs can run locally to populate their `local.js` file
  - Update README to use this script
- Definition of Done: ~the variables are named more clearly~
  - There is a script that devs can run locally to update their `local.js` file

accessKeyId and access_key_id are too similar.

**Comment by jseppi** [comment]
We can't change `access_key_id` -- that's what the S3 service from cloud.gov uses and we have no control over it.

`accessKeyId` is technically changeable by us since that is what our code calls that variable, but that formatting follows our naming convention (camelCase).

Could we just update the README instructions to be a little clearer instead? I assume this is referring to this part:

<img width="360" alt="screen shot 2018-01-17 at 5 03 42 pm" src="https://user-images.githubusercontent.com/697848/35071978-6bf253fc-fba8-11e7-8704-bb1aaa761d1d.png">

**Comment by wslack** [comment]
Can we just say awsBuildKeyId or something like that so they aren't named so similarly? (this might be a dumb question)

**Comment by wslack** [comment]
I'm amenable to that if it keeps the local install simple.
