### ISSUE TITLE
Determine nomenclature for Federalist sites/repos

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1538]
### Description of feature or bug

Federalist has four kinds of partner repos/sites:

1. Partner repos/sites that we host (the general population). Partners can copy each other's repos at will in creating their own sites.
2. Selected partner repos/sites that we showcase or use to demonstrate the value of Federalist. 
3. "Generic'd" repos/sites that are intended to give folks a starting place when developing their sites, but without strong documentation. 
   1. Example: https://federalist-report-template.18f.gov/, derived from https://cyber.dhs.gov/
4. Repos intended to give folks a starting place when developing their sites with strong documentation.

### Definition of done

We have a common nomenclature for all of the above categories.

### Level of effort: 

@OpenGlobe to evaluate: low/medium/high

**Comment by annahsebok** [comment]
Hey folks! A few clarifying questions — 

1. Are you looking for a single term that represents **all** of these four kinds of repos/sites or one for each? 
2. Have y'all done any research with users on this?
3. Is your goal to identify a buzzword or specially branded name to refer to these, or are you looking to identify a general term that could be used when referencing these? Ideally this goal would be based on research, but I understand if that hasn't been possible.
4. If you're leaning towards a general term, I'm wondering what (if anything) y'all perceive to be ineffective about the word `site`? From an outsider's perspective, I have a hypothesis that most users likely refer to each of these repos/sites this way already, and that identifying a different nomenclature could confuse them.

**Comment by wslack** [comment]
@annahsebok to check if in content rules

**Comment by annahsebok** [comment]
In our [content rules](https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit), it seems we prefer **website** (for first mention) or **site** (for subsequent mentions) when referring to Federalist sites, though there's no reference of the word **repository** so I'm not sure if that was even discussed as an option when these content rules were developed. 

That said, I'd suggest we stick with the term **site** when referring to 1 and 2, and the term **template** when we're referring to something otherwise known as a "starting point" (like the types of sites mentioned in 3 and 4). Repository is a technical term that should really only be used within our documentation/manual or GitHub training, not general sales material.

Let me know if I'm missing something here though @wslack.

**Comment by wslack** [comment]
I used "repo" in this issue to avoid bias, I think editing in **template** to the content rules makes sense.

**Comment by annahsebok** [comment]
Sounds good @wslack! I can tackle when I'm back in office.

**Comment by annahsebok** [comment]
I did this work forever ago and totally forgot to self-assign and move this to done. Sorry about that @wslack! This issue is all good now (the work was finished before we moved into our new backlog).
