### ISSUE TITLE
Rewire example sites page: Now Case studies!

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1566]
#### Description of feature or bug
Based on test results (#1561)

#### Definition of done
New wires!

#### Level of effort
~low~ medium+

**Comment by jseppi** [comment]
Why is this labeled as "blocked?"

**Comment by wslack** [comment]
removed blocked label; Issue is still marked as such in zenhub. If we want to prioritize it, we'll put in the "blocked" column to regularly check on status.

**Comment by ericronne** [comment]
Proceeding with caution for now, to be revisited when research catches up

**Comment by ericronne** [comment]
Wire for discussion and testing!
@wslack @thebestsophist @ShannonBad 

![case studies wire](https://user-images.githubusercontent.com/9259185/36867433-b3a0de20-1d5a-11e8-8f83-19e99bcc2ae2.png)

Happy to run through rationale for various decisions reflected here.

**Comment by wslack** [comment]
One thing we can't show here: the diversity and power of federalist sites (we don't do that well in the status quo either). Would there ever be a way/reason to show more example sites?

**Comment by thebestsophist** [comment]
@wslack do you mean like telling more of the story of the impact these sites have made?

We’d need some time create content to tell those stories, but I like that idea a lot.

**Comment by wslack** [comment]
Yes and I want to show more than 3 to show the diversity of our sites. We can't write up all 100 but I want to represent them somehow, if that makes sense. What if we do awards in various categories for our sites?

**Comment by el-mapache** [comment]
One approach that I think could be neat is to have each of these sections focus on a specific feature, and then describe how an agency or two have used those features to make their sites.

So, rather than make each app the focus of the section, make the feature the focus, and the partner site the complimentary piece. It would probably be most interesting with sites that stretch Federalist a bit, like the DOI project.

**Comment by jseppi** [comment]
I think that is a spectacular idea!

**Comment by ericronne** [comment]
What are some features that might be the broadly applicable to potential clients?

**Comment by jseppi** [comment]
quick thoughts:

- branch previews
- speed of launching a new site
- templates
- `hugo` as a build engine for very large sites (digital.gov)

**Comment by ShannonBad** [comment]
@ericronne RE: the wireframe design. This is a great! I really like seeing new ideas. I do think we should do some user testing, if we do this. 

I have an iteration on @thebestsophist idea, we may want to consider highlighting (in the section title) the type of website/template theme used - and then adding the title of the agency/website as a secondary part of the design. Since ideally we want clients more focused on our product. I made a super rough sketch (below) to share just to explain the idea better (I am sure it doesn't conform to the 18F style guide).

We may also want to revisit how we name templates?

![sample](https://user-images.githubusercontent.com/35078464/36922474-c5df1698-1e1c-11e8-87a9-a292d0b27053.png)

**Comment by wslack** [comment]
adding to what James posted: 

- branch previews (example: interior)
- speed of launching a new site (example: DHS)
- templates (example: US PCLOB)
- `hugo` as a build engine for very large sites (digital.gov) (example: as said)
 - static sites + API = dynamic experience with a tiny attack surface (example: scorecard)
 - making it easy for contractors: (examples: fedramp.gov and fedsim.gsa.gov)
 - opensource: markdown-editor.18f.gov and slides.18f.gov

**Comment by wslack** [comment]
@ShannonBad I think we want a separate page for templates apart from case studies.

**Comment by ShannonBad** [comment]
@wslack This is a seperate page for case studies still - it's highlighting which template was used, since the purpose is to have a client better understand how to use the Federalist templates, the template name should be used/searchable. Perhaps it's not top level in the final design, but it should be included IMO.

**Comment by wslack** [comment]
I'm confused. I think there should be two pages - one about case studies, one about templates. The case studies page should say what template was used, but the page will focus more on features of Federalist. Whereas, a templates page is focused more on what "you" the new customer can do.

**Comment by ericronne** [comment]
New wireframe for discussion! 

@thebestsophist @wslack @ShannonBad 

![case-studies-wire-v2](https://user-images.githubusercontent.com/9259185/37228644-f07e7a9e-23a6-11e8-9df0-fe5b81cd0efb.png)

**Comment by thebestsophist** [comment]
How about for the clients section keep it even simpler with “All our clients” or something like that and the all the logos, without any framing text? 

And then below that is a 1–2 sentence call to action and the contact button/link.

**Comment by wslack** [comment]
I think this page is beautiful and I agree with @thebestsophist about just having lots of screenshots of other live sites. (I wouldn't use agency logos here); there's a spot for those on the homepage.

**Comment by ShannonBad** [comment]
I think it's looking better! Could the links to the websites actually be the image (instead of more text below the image)? Maybe with a tool tip on the image, to remind people they can see this elsewhere? 

I think in the research it was mentioned that people wanted to see highlights of what was done well with the templates, but on other client sites. Is that what this main body client text is?

**Comment by wslack** [comment]
👍 I think we may want the text as well to make it explicit though, for people that don't mouseover the image (or we can test that). I think we'll have a separate template specific page, but the case studies that use a template will do well (however, most of the most impactful federalist sites were custom designed in some way).

**Comment by ShannonBad** [comment]
@wslack I think your point, _"but the case studies that use a template will do well (however, most of the most impactful federalist sites were custom designed in some way)"_ is something that could be mentioned in case studies as "custom design"? I honestly had no idea you could even customize your Federalist site that much, I assumed it was limited in design like a CMS (and "A2" in user research testing said the same).

**Comment by wslack** [comment]
Good point! I had thought I showed you the "back end" of a federalist site earlier but the short answer is that any static HTML can be hosted on Federalist. There are no CMS like design constraints, but also no drag and drop design tools.

**Comment by ericronne** [comment]
Further draft …

![case-studies-wire-v3](https://user-images.githubusercontent.com/9259185/37295493-57be9b8a-25e6-11e8-99d3-ba6186fc004f.png)

**Comment by wslack** [comment]
Ready for Eric to take the next pass!
