### ISSUE TITLE
"Add your own repository" form validation could be friendlier

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1584]
#### Description of feature or bug
Real-time error checking for the repo-add form on the [New site page](https://federalist.18f.gov/sites/new) throws a jarring error from the first character a user enters.

![image](https://user-images.githubusercontent.com/9259185/35736191-c00d46cc-07ec-11e8-8cf4-81115b32b9b0.png)

Perhaps we should wait for users to hit submit before validating in this case.

#### Level of effort
Low

**Comment by wslack** [comment]
I feel like we changed away from the behavior desired for a reason but am not sure. Agree its jarring.

**Comment by jseppi** [comment]
It doesn't actually happen on the very first character entered; rather, it takes first entering some text, then moving focus away (at which point validation is triggered). After the validation gets initially triggered, then it starts validating on every character.

![repo-url-validation](https://user-images.githubusercontent.com/697848/35741085-7fbb35d8-07fc-11e8-8372-31c7f81d5016.gif)

We're probably more aware of it because we use this form way more than our users do (since they don't add sites as frequently as we do as).

**Comment by ericronne** [comment]
Lo and behold. I'd say this is fine, then. Agree @wslack

**Comment by wslack** [comment]
ah, yes, agree.
