### ISSUE TITLE
Design a friendly and helpful 404 page

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1593]
### There is no design for the 404 page
![image](https://user-images.githubusercontent.com/9259185/35869527-e4546886-0b24-11e8-897e-cb47abec0f1f.png)

### Definition of done
We've implemented error page which puts users at ease and helps them find their way.
- [x] Write
- [x] Design
- [x] Implement

### Level of effort
Medium

**Comment by jseppi** [comment]
We also have this one, but it can only be reached under very specific conditions:

<img width="1126" alt="screen shot 2018-02-06 at 11 10 41 am" src="https://user-images.githubusercontent.com/697848/35873129-6e218b9e-0b2e-11e8-87f8-77a9d2891745.png">

**Comment by alexsoble** [comment]
Since a running theme in this issue is "screenshots of the current state of the 404 page" ... here is the current state of the 404 page (which we want to refresh/replace): 

<img width="589" alt="current-state-federalist-404" src="https://user-images.githubusercontent.com/3209501/52076923-6c3e9780-2555-11e9-808e-d2bdfa5c6576.png">

**Comment by alexsoble** [comment]
Design goals, screenshots and more here: https://github.com/18F/federalist-garden-build/pull/155.

<img width="370" alt="404-chrome-galaxy" src="https://user-images.githubusercontent.com/3209501/52077083-b889d780-2555-11e9-95a2-05722796c481.png">

**Comment by alexsoble** [comment]
I'll also add that the lines of code we edited here — https://github.com/18F/federalist-garden-build/pull/156/files — had no effect on the production 404. The actual 404 file is pulled in from elsewhere. A good future refactor would be "delete lines of code that look like they're setting up 404 but aren't," I'd be happy to tackle that.

**Comment by jseppi** [comment]
_from the darkness, a ghostly apparition swirls into existence_

The 404 page referenced in this issue is for the Federalist web app -- the one at https://federalist.18f.gov.

The 404 page in federalist-garden-build, that was modified in https://github.com/18F/federalist-garden-build/pull/156/ is for _client_ sites. There's no link between that one and the one in this repo.

_poof_

**Comment by alexsoble** [comment]
@jseppi Ooooh! Wow! Thanks, that was a very very helpful apparition! 👻 

@eddietejeda Maybe we can edit this issue description to make it clearer that this is for the federalist web app? And make a new Issue for client site 404 pages?

**Comment by amirbey** [comment]
404 page for federalist client sites has its own issue #2129
