### ISSUE TITLE
Refine Information Architecture (IA)

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1723]
#### User Story
As a Federalist content owner, I want information about how the content should be organized from user testing.

#### Background
We need to test the information architecture of the Federalist website to assess how users natural navigate through site content. This will improve navigation and wayfinding, helping future customers understand what the product is.

We'll start with a card sorting exercise to collect data from users about their mental model when they encounter various types of information available on the Federalist sales website. After refining our IA based on our findings and other research, we should do tree jack testing to validate (via #1856).

Note: further research with more diverse users may modify the IA further

#### Acceptance Criteria

- [x] Diagram of validated Federalist site architecture with a research document of the synthesized data.
- [x] There are new issues added to the repo outlining the various steps we need to take to update the structure of federalist.18f.gov and federalist-docs.18f.gov based on the IA diagram.
 
#### Level of effort - medium

- [x] Build card sort
- [x] Conduct card sorting to gather additional user insights to further inform [IA](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4) 
- [x] Analyze findings
- [x] Incorporate card sorting findings and research findings (from completed research and research being managed in #1787) into IA

**Comment by ShannonBad** [comment]
This is a result of the team discussion around the creation/voting for an action plan
https://docs.google.com/document/d/1mcUzYMQ7Op9fRKp-RvYOLVpiFmLOKghtaT4ljmnQlVc/edit?usp=sharing

and from the - creation of a final user research document for testing the homepage #1667

**Comment by ShannonBad** [comment]
Link to the **User Research Interview Plan** for existing Federalist Users not working within TTS (currently in progress): https://docs.google.com/document/d/1BJg2HvNA3ab_m-lMrCZlfSomCelZ_g9nh_MOvPpywe4/edit?usp=sharing

**Comment by annahsebok** [comment]
Here's the IA that @thebestsophist created https://app.mural.ly/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4

**Comment by ShannonBad** [comment]
Various testing tools (per convo with Anna) -  https://www.optimalworkshop.com/features

**Comment by annahsebok** [comment]
I definitely recommend we start with card sorting to collect data from users about their mental model when they approach various kinds of information. We should take that + research findings and refine the IA @thebestsophist created, and then consider doing treejack testing to validate it.

**Comment by ShannonBad** [comment]
@annahsebok do you think I should seperate this issue into two different github issues? I will still be creating the user research for existing users (from a sales perspective) but per our convo, maybe I should have the IA and testing separated from the ongoing research/service design?

**Comment by annahsebok** [comment]
@ShannonBad yea, based on the original issue, I'd say let's focus here on the IA testing (for which it looks like the implementation steps above are pretty close) and then probably create a new issue for the ongoing research and service design work. Otherwise this could become quite the epic (as opposed to discreet research tasks).

**Comment by ShannonBad** [comment]
Done ✅ - these issues are now separated and on two different GitHub issues.

**Comment by annahsebok** [comment]
Updated issue to reflect our new [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#).

**Comment by annahsebok** [comment]
Card sort is built and I am testing it [here](https://usagov.optimalworkshop.com/optimalsort/federalist) with members of #federalist-private in Slack. Once I've gotten some feedback from the team, we'll be ready to launch this with users!

I'd like to for us to run this card sort for the last 15 minutes or so of our user interviews so we can capture real-time reactions. To increase our data, I also plan to shit it out to TTS via Slack/email.

**Comment by amirbey** [comment]
Feedback on Card Sort
"A fact sheet for federalist."  - what kind of facts?  I felt it could be a little more specific

**Comment by adborden** [comment]
Feedback on Card Sort:

Great! 51 cards is a lot, so maybe set expectations at 15-20 minutes. I like the card content and liked that some were more ambiguous. It made me think.

What was unclear is if the sorting within the group is important or not. It wasn't mentioned in the instructions, but I was a little uncomfortable that maybe some cards withing a group were deemed more important than others because they were at the top. That is not the case. Sorting within the groups would've taken quite a bit longer.

**Comment by jmhooper** [comment]
Feedback on Card Sort:

The card for describing "the components of Federalist" was a bit vague to me. Does that mean the different backend components, or the different things you see when you log in to the site, etc?

The card describing how Federalist works with cloud.gov also struck me a little vague. I wasn't sure if the audience for that would be developers working on Federalist, or if that was supposed to be marketing.

**Comment by karareinsel** [comment]
Just an FYI -the exercise took me 20 - 30 minutes to complete. That might be due to my lack of familiarity with Federalist. 

Also, do we want to include a short description of the differences between these two sites mentioned in the pre-card sort screener? I suspect that many users don't even realize they're on two different Federalist websites.
<img width="1028" alt="federalist card sort" src="https://user-images.githubusercontent.com/34074929/39377027-b3879f5c-4a21-11e8-9b51-dee6ade356aa.png">

**Comment by annahsebok** [comment]
@adborden you can ignore my previous comment. I got you!

**Comment by wslack** [comment]
@annahsebok reminder to put in some screenshots from the testing results and summary of results here! (or in a GDoc)

**Comment by annahsebok** [comment]
High-level summary: Roughly 1/4 of users sorts all Federalist content into 4 buckets - `Features & Pricing`, `Example sites`, `Contact`, and `Support`, with `Support` being the largest bucket by far and including all of our documentation, demos, integration details, customization information, and template guidance. I'm using that + some of the additional levels users identified during card sorting to refine [our IA](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4) a bit further and will be adding tactical action steps we should take to reflect the outputs of our research in this issue this week.

**Comment by annahsebok** [comment]
A few interesting images from our card sort analysis options in Optimal Workshop include:

A similarity matrix that shows how similar two topics are to our users given how they were sorted. (The 4 bottom rows that are cut off are "What is GitHub," "Demos for how to use GitHub," "How Federalist and GitHub work together," and "How to contribute to the open source code for Federalist.")

<img width="1164" alt="screen shot 2018-06-11 at 11 50 11 am" src="https://user-images.githubusercontent.com/6728448/41248258-b155b90c-6d6d-11e8-8562-d8225b3105a9.png">

Another interesting view of the data is the skeptical dendrogram, which again visualizes the relationships users identified between different topics. 

<img width="1207" alt="screen shot 2018-06-11 at 11 52 45 am" src="https://user-images.githubusercontent.com/6728448/41248330-f1a7cfa4-6d6d-11e8-9ae8-843fffa5465c.png">

I'm working predominating off of the participant-centric analysis that Optimal Workshop produced when refining the IA, and here's what that looks like (though a lot is cut off due to screen size). 
<img width="673" alt="screen shot 2018-06-11 at 11 54 07 am" src="https://user-images.githubusercontent.com/6728448/41248392-279e36b6-6d6e-11e8-98d7-f4a6ee056ac7.png">

**Comment by annahsebok** [comment]
I've removed

> - [ ] Build tree jack test 
> - [ ] Conduct tree jack testing to validate new IA
> - [ ] Incorporate tree jack testing findings into IA

From this issue description — these will go in another issue for further refinement to the IA at a later date once the site has been updated with the new structure we're finalizing now. I'll add that subsequent issue soon.

**Comment by annahsebok** [comment]
Just finished our card sort analysis and incorporating findings into [the new IA](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4). @wslack I'd love for you to take a look and share any thoughts or feedback. Friendly reminder that this organization is 90% based on feedback from users with little to no experience using Federalist. The remaining 10% is based on a few assumptions I'm making that I think we'll validate in #1856 once structural changes have been made to both sites.

As for the incremental work to make subsequent changes to the site (per the second acceptance criteria that I just added), I'm chatting with @AlanAtlas later this morning about how to best represent them in our repo (either here in this issue or opening others).

**Comment by annahsebok** [comment]
I spoke with @AlanAtlas and am going to file separate issues to cover the subsequent work as an outcome of this work. I've updated the acceptance criteria to reflect that.

**Comment by annahsebok** [comment]
Created #1820, #1869, and #1885 as outputs of this work. Still have one more issue to update and will flag here when it's done!

**Comment by annahsebok** [comment]
Final output update: I've refined https://github.com/18F/federalist-docs/issues/212 to adequately capture the IA migration work that needs to happen on the support site (federalist-docs.18f.gov).
