### ISSUE TITLE
Get Josh Bruce's experiment working

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1790]
#### Description of feature or bug

https://github.com/joshbruce/sam-design-system-site

#### Definition of done

- [ ] Josh's site is building at onepagetest.18f.gov

_After evaluating, edit this part:_

**Comment by wslack** [comment]
- [ ] Updated the terminal to point to the site vs a preview build

**Comment by el-mapache** [comment]
@wslack Re: '#' appearing in the URL, we might want to have josh check out the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History). This is what routers for Ember, React, etc use to rewrite URLs cleanly in single page apps. I haven't used angular since 1.x but I can almost certainly guarantee there is a library made for this.

**Comment by wslack** [comment]
@el-mapache thank you and we got it fixed! Check out onepagetest.18f.gov now.

**Comment by el-mapache** [comment]
What did you end up changing to resolve the issue?
