### ISSUE TITLE
Federalist Homepage Content Suggestions

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1820]
##### Rely on Federalist to do the heavy lifting

Each blurb (“Easy, powerful and fast” or “Fully customizable”) should link to that specific page on the Documentation section

##### Kickstart your website with one of our templates

Consider removing “Jekyll” from the copy - depending on the prospect’s tech savviness, if they aren’t familiar with Jekyll, they might automatically dismiss Federalist from consideration since they might assume it’s not right for them since they don’t know what Jekyll is. The messaging would still work if it was rewritten to say “Customize one of our 508-compliant Jekyll templates so you can spend more time on your content.”

##### Launch your site in minutes

- Change to "Deploy site updates in minutes."
- Move client logos to bottom of page - closer to the footer
- Align style of logos so that there's less visual cacophony
- Consider removing names of agencies

#### Definition of done

- [ ] Rely on Federalist to do the heavy lifting

- [ ] Kickstart your website with one of our templates

- [ ] Launch your site in minutes

_After evaluating, edit this part:_

**Comment by annahsebok** [comment]
I just noticed this issue and have feels:

1. We're making some homepage changes over in https://github.com/18F/federalist/pull/1870. I think that's a great iteration on simplification.
2. On **Rely on Federalist to do the heavy lifting** - Similarly to my remarks in the PR above, I hesitate to add a ton of links to the homepage because it can be overwhelming to users when first visiting a site. If we want to link to documentation, I'd recommend those links live in the features page content where everything is much more granular and could benefit from documentation links.
3. On **Kickstart your website with one of our templates** - I definitely encourage us to stick with `Launch` over `Deploy` on the homepage, which is a technical term and could make folks nervous. I'd also suggest we move any info related to a specific agency to the `Example Sites` page and remove it from the homepage (this is based on user feedback during our card sort).

**Comment by wslack** [comment]
👍 these will wait at a lower priority and may be eclipsed.

**Comment by eddietejeda** [comment]
This issue is now being tracked here: https://github.com/18F/federalist/issues/2153
