### ISSUE TITLE
Usability edits to main federalist app

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1851]
#### User Story

A technically savvy but new Federalist user had trouble executing some workflows in Federalist because of poor usability.

- As a user of Federalist, I want to see all of my logs on the "builds" screen or understand that they are scrollable.

#### Background (Optional)

The user didn't realize that the error message was scrollable. We can mitigate that with an outline.

#### Acceptance Criteria

- [x] Consult with content designer on language and confirm acceptance criteria.
- [x] The logs column contents are surrounded by an outline.

_After evaluating, edit this part:_

**Comment by wslack** [comment]
@coreycaitlin when you have a 15 min, we should talk about this one before I do the code changes!

**Comment by coreycaitlin** [comment]
Here's how I would recommend revising this bit of interface:

<img width="801" alt="screen shot 2018-06-20 at 4 37 31 pm" src="https://user-images.githubusercontent.com/1450354/41690001-648ef83a-74a8-11e8-9d69-0909adfbbaea.png">

This means:

- Adding a mini header above the log output so people have more immediate context for what it is (especially since the column header is _way_ above this text)
- Add a light border around scrollable log output — this should help people see this as a scrollable box
- Putting "view logs" and "restart build" on separate lines
- Lengthening "Restart" button text to "Restart build" so people know _what_ they're restarting (other options include "Build again" or "Rebuild this branch")

I think these changes will:

- Help users understand that the logs are scrollable at a glance
- Understand how to restart a failed build
- Make this interface cleaner

**Comment by wslack** [comment]
To look at Monday with @adborden

**Comment by wslack** [comment]
Scrollbars.

Turns out the bars appear or disappear based on if I have my mouse plugged in per this OSX option I don't recall ever changing (and sometimes the page changed without a refresh!). @hbillings and I are both curious if we can make CSS force the bars to always show up.

![screen shot 2018-06-25 at 4 42 25 pm](https://user-images.githubusercontent.com/10016577/41875122-f22fed6e-7897-11e8-9b4b-a3399e09224b.png)

**Comment by wslack** [comment]
This is how they appear when I have my mouse plugged in
![screen shot 2018-06-25 at 4 52 14 pm](https://user-images.githubusercontent.com/10016577/41875196-21905f80-7898-11e8-9c88-426b41eb2c80.png)

**Comment by hbillings** [comment]
@wslack I think you're going to need something like this: https://stackoverflow.com/questions/7855590/preventing-scroll-bars-from-being-hidden-for-macos-trackpad-users-in-webkit-blin

You _might_ just be able to get away with a background color on the scrollbox rather than implementing CSS scrollbars. With a background color and no bottom or right padding, text that overflows would touch the edge of the element. That might be enough to hint to someone that they can scroll the box.

**Comment by wslack** [comment]
Let's do an outline!

**Comment by wslack** [comment]
aka "border"

**Comment by wslack** [comment]
Already merged, doesn't need to be covered in sprint review.
