### ISSUE TITLE
Iterate on case studies/example sites page

### ISSUE THREAD

**Issue by annahsgraves** [18F/federalist#1885]
#### User Story

As a user, I want to see examples of sites built of Federalist so that I can learn how people have used Federalist to suit their various needs. 

#### Background (Optional)

It's clear from the card sorting exercise we did with users that people are interested in a page on Federalist.18f.gov that outlines a variety of example sites so that users can see how others use Federalist. We captured that need in [our IA](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4). While we do have [a case studies page](https://federalist.18f.gov/case-studies/) up right now, we need to make some changes to that page.

#### Acceptance Criteria

- [ ] New example sites have been added
- [ ] More contextual information around the use of template has been added
- [ ] Federalist stats have been moved from the homepage to this page
- [ ] Agencies using Federalist have been moved from the homepage to this page
- [ ] This page links to blog posts and/or news articles about Federalist sites

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Review https://github.com/18F/federalist/issues/1681 for past context of work (that issue was closed in favor of this one)
- [ ] Incorporate explanations for how each agency used a template into each example
- [ ] Move `Federalist stats` from homepage to this page
- [ ] Move the list of agencies using Federalist from homepage to this page
- [ ] Incorporate seedfund.nsf.gov example
- [ ] Incorporate plainlanguage.gov example
- [ ] Incorporate revenuedata.doi.gov example (and remove from `see more sites powered by Federalist` list)
- [ ] Incorporate pclob.gov example
- [ ] Consider other examples to add (possibly cio.gov, 18f.gsa.gov, and fedramp.gov)
- [ ] Add to `see more sites powered by Federalist` list 
- [ ] Add content module or section that calls out any blog posts or new articles about Federalist websites

**Comment by annahsebok** [comment]
@wslack I recommend this work be prioritized between #1869 and #1805 in the backlog but ultimately defer to @coreycaitlin. Also this new issue captures a lot of other piece-meal issues — I'm going to note this issue in each of those and suggest we close those to clean up the backlog and holistic case studied approach.

**Comment by annahsebok** [comment]
Here is the [long-form case study for NRRD}(https://docs.google.com/document/d/1nvsyM1-PmCFWBxHor-IuWZmzAQNm4mREdRw-VJ6pIr0/edit) from where we were still planning to write longer pieces about each site. We heard from a marketing assessment that these longer form pieces are likely to be less valuable to users, which is why we decided to refocus on and prioritize expanding on the existing case studies page in it's existing format.

**Comment by wslack** [comment]
👍

**Comment by wslack** [comment]
@annahsebok that's a pretty high ranking - you would put this above the new IA?

**Comment by annahsebok** [comment]
@wslack this work is a part of executing the new IA. I suggest that prioritization because you've previously prioritized the marketing site over the support/docs site. If you'd rather focus on the support site first, this could totally go after https://github.com/18F/federalist-docs/issues/212. Either way, it should definitely be done before #1856.

**Comment by eddietejeda** [comment]
This issue is now being replaced by this https://github.com/18f/federalist-team/issues/24
