### ISSUE TITLE
Figure out how to handle baseurls

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#193]
Right now, we rely on baseurls for the preview links on the application. However, that can get in the way of links in the markdown editor since we have to use syntax like:
` {{ '/assets/files/my-doc.pdf' | prepend: site.baseurl }}`

One option is for us to use subdomains instead of baseurls.

**Comment by dhcole** [comment]
Subdomains seem pretty tricky with CloudFoundry since it would require a wildcard route on a sub-sub-domain.

How about we build out the link button in Prosemirror to be smarter? Looks like this is an example on how to do that: http://prosemirror.net/demo_dino.html

To start, the input could be formatted as the liquid tag with the baseurl of the url doesn't begin with `http[s]:`. We could expand this so the link interface had a dropdown of pages by title, which from Prose, we found was much easier for users to create links (they're used to thinking of linking to a page, not to a url).

**Comment by dhcole** [comment]
I think we could do the same kind of thing to extend the image button to browse locally saved images.

**Comment by jeremiak** [comment]
Yup, I think we can actually do that in a few different cases. Raw liquid could be one, we can override links to the behavior you're talking about, and this can also be useful for the includes you're talking about in #191

**Comment by dhcole** [comment]
This requires extending prosemirror, for which better documentation is on the way. Moving this out of the milestone for now. Let's check back on it in a week.
