### ISSUE TITLE
Better document how the 404s work

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1970]
#### User Story

As a Federalist user, I want to understand how 404s for my site work and what my options are for configuring them.

#### Background (Optional)

1. We make 404 pages in each build
2. We do custom CloudFront
3. We have one big default 404

#### Acceptance Criteria

- [x] A user can learn what all of the possible 404 pages are and how to configure for each!
- [x] Change made live via <TODO>.

_After evaluating, edit this part:_

**Comment by davemcorwin** [comment]
@eddietejeda @amirbey How is this for content and accuracy?

(Added to the "Customizing your site" section)

## Custom 404 pages
If a user navigates to a page on your site that does not exist, they will see a “404 Page” (webspeak for a page that doesn’t exist). Federalist provides a default 404 Page (shown below), but you may prefer something that looks and feels like it is part of your site.

#### Federalist Default 404 Page
![default-404](https://user-images.githubusercontent.com/6662371/53976338-a9012f80-40bb-11e9-9075-4e65e1b94d4e.png)

In order to use a custom 404 Page, name your 404 Page "404.html" and make sure it is included in the resources that are deployed (For Jekyll sites or sites with no build process it should be in the root of your project). Then, let #federalist-support konw that you would like to use a custom 404 page named "404.html" and we willhandle the rest.

**Comment by amirbey** [comment]
yes ... looks good to me ...

**Comment by wslack** [comment]
❤️ (I'm going through GitHub notifications and seeing all of these updates is 😄)
