### ISSUE TITLE
A more clear login button

### ISSUE THREAD

**Issue by jeremyzilar** [18F/federalist#2118]
#### User Story

As a federalist user, I would like it to be more clear how I can log in to Federalist to manage my sites.

One of these links in the nav is not like the others. That is the "Manage Sites" link.
![image](https://user-images.githubusercontent.com/395641/51929340-f9eb7d00-23c5-11e9-83a0-48cd59ed2f9a.png)
It would be great if it were more button like.
Also not sure if `manage sites` is the right copy here... but you can figure that out better than I can :)

**Comment by davemcorwin** [comment]
Lets think about what the nav and  the "Manage Sites" link/button does in different contexts. When on the marketing site, the "Manage Sites" link is really a link to the app, while when on the app its a link to the home page. I think we should consider differentiating this a bit more. Images of everything below.

For the marketing site "Manage Sites" link, I think it makes sense to use button styles and maybe even change the text to something like "Go to App" or "Log In"

For the app, I think we can remove it altogether or change the text to "Sites" since we have the logo on the lefthand side.

We should also consider moving the links that return to the marketing site to the footer instead so its clear that it takes you away from the app. Perhaps with the excption of "Support" which could be changed to "Documentation" since I can see a user of the app wanting to go to the docs, otherwise, i don't see a user of the app wanting to navigate back to the marketing site.

@eddietejeda @amirbey @amirahaziz Curious on y'all's thoughts.

### Marketing Nav
![marketing-nav](https://user-images.githubusercontent.com/6662371/54380717-699d8a80-4649-11e9-9147-3ebec25037e9.png)

### App Nav Authenticated
![app-nav-authenticated](https://user-images.githubusercontent.com/6662371/54380753-7a4e0080-4649-11e9-8e7c-01db7a09301f.png)

### App Nav Not Authenticated
![app-nav-not-authenticated](https://user-images.githubusercontent.com/6662371/54380779-83d76880-4649-11e9-9d62-bfc6ee38e7fb.png)

### App Footer
![app-footer](https://user-images.githubusercontent.com/6662371/54380819-96ea3880-4649-11e9-98b6-d5815a829f30.png)

**Comment by davemcorwin** [comment]
@eddietejeda any thoughts on this?

**Comment by eddietejeda** [comment]
I think you are like right about "Features", "Case Studies", "Manage Sites" and "Contact". Those don't need to be in the app. We can remove those. Adding the links to the footer is fine.

For the marketing site, I think it needs to say "Manage Sites" and not "Login", since it will always say "Login" even when you are already logged in. I don't think "Go to App" is right either. Thats revealing an implementation detail to the user that I don't think is necessary.  As a user, how do I know what the "App" is? From their perspective it's all just a site. I think "Manage Sites" is more relevant from what they are trying to accomplish, which is managing their sites.

**Comment by davemcorwin** [comment]
@eddietejeda sounds good, let me know if you have any feedback on the following.

## Todos
1) Use the white button style for the "Manage Sites" link on the marketing page.
2) Move "Features", "Case Studies", and "Contact" links in app from nav to footer
3) Remove "Manage Sites" link from app nav

## Questions
1) You want to leave the "Support" link unchanged? It links to documentation, when I see support, I think it links to an areas to contact Federalist for help
2) Do you want to leave the "Home" link in the app nav? We have the logo which is already a link to the home page and when not authenticated, the user will be on the home page

**Comment by eddietejeda** [comment]
1) In the 'restructure_pages_directory' branch, support goes to it's own section. I removed the link from the sidebar though. Lets do it like that.
2) Lets get rid of "Home"

**Comment by eddietejeda** [comment]
This now in production
