### ISSUE TITLE
Why does the value say "script only"?

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2232]
https://github.com/18F/federalist/blob/6d8f1f4cbe0b9757e627ca6f2e4dc8d6a1744d50/frontend/components/SelectSiteEngine.jsx#L15

**Comment by apburnes** [comment]
It's used in (federalist-garden-builder)[https://github.com/18F/federalist-garden-build/blob/739c49b50cf4f8e20e8b8486c1d90a53ef8f32ad/tasks/main.py#L277-L278]... kinda.

**Comment by eddietejeda** [comment]
would changing it to nodejs break things? I think we should be clear with what it means.

**Comment by apburnes** [comment]
Would probably just need to update the `federalist-garden-builder` to reference the updated keyword and any setting referring to the engine as `script only` in `federalist`.

**Comment by amirbey** [comment]
@eddietejeda - we agreed this change was initially cosmetic ... making changes in build container

**Comment by amirbey** [comment]
#### User Story

<TODO>

#### Background (Optional)

Display Node.js to users instead of script only.  Initially, changes cosmetically, but would like to rid of "script only" throughout codebase

#### Acceptance Criteria

- [ ] change engine value of "script only" to "node.js"
- [ ] update the garden-build from script only to "node.js"
- [ ] update site.engine to "node.js" for entries where site.engine='script only' in staging
- [ ] Change made live via deploy to Federalist staging
- [ ] update site.engine to "node.js" for entries where site.engine='script only' in production
- [ ] Change made live via deploy to Federalist production

_After evaluating, edit this part:_

#### Level of effort - Low

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
https://github.com/18F/federalist.18f.gov/pull/317
