### ISSUE TITLE
Soft delete branches page

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2634]
#### User Story

This page is not all that helpful, folks can view their branches from Github.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] Page doesn't exist
- [x] Change made live via deploy of Federalist

#### Implementation outline (if higher than "low" effort):

- [ ] Remove page

**Comment by davemcorwin** [comment]
The data for this page is pulled straight from the Github API so we don't necessarily have the data in the client to show the latest deploy url for each branch. Given that a repo's branches are just available on Github (Ex. https://github.com/18F/federalist/branches) I'm thinking about removing this page entirely. That said, there may be a use case for finding a deployment based on branch that would be hard with the current builds page since it could be buried.

What about removing the branches page (maybe adding a link to Github somewhere) and adding an affordance on the build page to filter by branch? 

@amirbey @apburnes

**Comment by amirbey** [comment]
i doubt how much this page is used and feel its removal has been re-surfacing topic.  on occasion, i have used the GitHub tabs for support to rebuild branches but can't think of a scenario where I couldn't have rebuilt the branch from the site builds page. that being said .... i think we can get rid of it
