### ISSUE TITLE
Add Site: adding a github repo should use accurate default branch

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2761]
#### User Story

When a user adds a new site to Federalist using an existing repository, their live branch should reflect the default branch of their repository.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] when adding a new site to Federalist using an existing repository, the live branch should reflect the default branch of their repository.
- [x] Change made live via deploy o Federalist

_After evaluating, edit this part:_

**Comment by davemcorwin** [comment]
## Current state
On the "New Site" page, when the user submits a Github URL, the API attempts to add the user to the site. If this fails with a 404 (due to the site not existing in Federalist), the UI displays the "site engine" and "primary branch" fields for the user to update and submit. Once submitted, the API invokes the logic in `SiteCreator` to create the site. This is point at which the API communicates with Github to verify the actual repository details (existence, permissions, etc) before creating adding the site to Federalist or returning an error.

## Proposal
1. On the "New Site" page, replace the affordance to configure the "primary branch" with a message along the lines of:

> The primary branch for this site in Federalist (the one typically used for your production deployment) will be initially determined by the default branch in Github. You can change this at any time in the Site Settings for this site.

2. When checking the existence of the Github repo, use the `default_branch` returned with the `repo` payload to set the default branch of the site in Federalist.

@amirbey @apburnes Thoughts?
