### ISSUE TITLE
Verify Github webhook API changes don't break Federalist

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#330]
Per this post (https://developer.github.com/changes/2016-03-15-new-webhook-actions/) Github is going to change the way the webhook requests are made, and recommend we check the `action` of the request before processing.

Based on the current [`WebhookController`](https://github.com/18F/federalist/blob/master/api/controllers/WebhookController.js) it doesn't look like we do an explicit check of the `action` value.

**Comment by suprenant** [comment]
Items to watch for: 
Federalist sites not building (does not seem to be an issue given builds seen to date)
Federalist building too many sites, not filtering appropriately

**Comment by jmhooper** [comment]
This should not be an issue for us since we only subscribe to the [webhook for push events](https://developer.github.com/v3/activity/events/types/#pushevent) which does not expose an `action`.

Figuring out filtering on `action` from this point would be difficult b/c we don't know what values we'd want to filter on. We could potentially check that `action === undefined`, but how we proceed from there is not clear either.
