### ISSUE TITLE
Evaluate cloud.gov product flow for use with Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#386]
https://github.com/18F/cg-product/blob/master/DeliveryProcess.md

**Comment by leahbannon** [comment]
This is great. For now, a few things I suggest we implement from this related to grooming issues:

* Make sure that everything in the Ready/Pr1 category has been groomed. 
* Have a staging category between Pr1 and Pr2 labeled Grooming. Use this instead of the "question" label.
* Grooming would include: 
  * Discussed by the team and implementation sketched (use more checklists here)
  * Definition of done is written
  * The scope of the work is easily doable in a few days (else split it!)
  * There's a communication plan for any changes that affect users

I am also a big fan of writing stories in ["in order to" first"](http://blog.crisp.se/2014/09/25/david-evans/as-a-i-want-so-that-considered-harmful) format. I suggest we do that for anything in Pr1 and Pr2 that relates to a user need or feature.

I think we should write a draft of these and other team processes in a week or two, once we've been doing them for a bit. 

After that, we should build a more robust team plan that includes more from the cloud.gov team's processes once a larger team is in place or we are ready to start conducting more micropurchases.

What do y'all think?

**Comment by wslack** [comment]
> There's a communication plan for any changes that affect users

Going to ID when we need a comms plan in grooming; do the plan in the actual sprint.

Otherwise this all looks good.

**Comment by leahbannon** [comment]
> Have a staging category between Pr1 and Pr2 labeled Grooming. Use this instead of the "question" label.

We decided to create a "needs grooming" label that we will add to everything in Pr2 column. We will focus on grooming issues that are at the top of the Pr2 column, especially prior to sprint planning meetings or when Pr1 starts running low.
