### ISSUE TITLE
Wireframe - First Time User States

### ISSUE THREAD

**Issue by bradnunnally** [18F/federalist#39]
Here are two wireframes which I think represent the initial state of Federalist if no one has used it before or have not created a site using Federalist yet. 

These wireframes are DRAFT, they have not been reviewed by any teammates or potential users. So everything is up for change. 
![federalist_wireframe_first_time_user](https://cloud.githubusercontent.com/assets/12515096/8114872/2d9dc6d0-103d-11e5-9d6f-b63e0745895c.png)
![federalist_wireframe_first_time_user_add](https://cloud.githubusercontent.com/assets/12515096/8114873/2d9eaa8c-103d-11e5-98fb-4c94f529b3c9.png)

Things that needs to happen with them:
 - Validate with potential users and teammates
 - Visual design 
 - UI Development

**Comment by jeremiak** [comment]
I like this idea of showing folks how to use federalist in the case that they haven't yet. My first reaction is that we shouldn't ask them to create any site before they authenticate with Github, but we still have to make the case for why they should go through that hassle.

Also, just quick note that the vie win the second wireframe isn't something we actually handle. We ship them off to Github and once they have successfully authenticated they come back with a token. The reason lots of sites have this style of workflow is so that the user only ever enters their passwords on pages owned and controlled by Github (which we like because that's one less thing we have to worry about :smile: )

**Comment by bradnunnally** [comment]
That makes sense. I'll make an iteration based on this feedback later today.

**Comment by dhcole** [comment]
Love these. Thanks @bradnunnally

**Comment by bradnunnally** [comment]
Another updated wireframe to simply the new user state. 

![federalist_wireframe_first_time_user](https://cloud.githubusercontent.com/assets/12515096/8185308/5f4abfda-1411-11e5-89bd-bad042257dff.png)

**Comment by dhcole** [comment]
Captured here: https://github.com/18F/federalist/wiki/Design-Documentation
