### ISSUE TITLE
Add search support or documentation

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#392]
(options edited in by @wslack)
Option 1: Use https://github.com/18F/jekyll_pages_api_search (used with Federalist on 18f.gsa.gov's blog page or for sites like our Content Guide. Check the Github repo for some detailed documentation. From talking to some devs, this is elegant in being located all in the front end but the index file will get big on large sites - it won't scale well)

Option 2: Use a backend API of your own making. NotAlone.gov (an old site being retired imminently) uses an API server 18F made to do search.

Option 3: Use DigitalGov search: http://search.digitalgov.gov/ (most likely choice, unclear how hard to implement per site or en masse)

**Comment by hbillings** [comment]
We've been having some conversations about this related to the Pages -> Federalist migration and upgrades to the [`guides_style_18f` gem](https://github.com/18F/guides-style). Namely, when used _in conjunction with the style gem_, the [`jekyll_pages_api_search`](https://github.com/18F/jekyll_pages_api_search/) gem that is required by `guides_style_18f` is not compatible with versions of Jekyll greater than 3.1.
_Note: the search gem seems to work just fine when used independently from the style gem, as can be seen with the 18F site._

My immediate recommendation is to *pin Jekyll to v3.1* within `guides_style_18f`. (Latest version is 3.3.1.) This will allow relatively painless upgrades for 18F Pages site owners. This is, however, not a long term solution, especially given how fast Jekyll development tends to move, and it will prevent site owners from updating Jekyll themselves.

###Option 1: Fix the search gem (or search gem/style gem integration issue)
This is technically possible, probably, though I've had a couple of smart folks pair on it with me to no avail. There also seems to be some uncertainty whether the issue is with the integration of the two gems, or just with the search gem. (See [this PR](https://github.com/18F/jekyll_pages_api_search/pull/41) issued against the search gem as an attempted fix.) This is likely to be more time-intensive than we want, unless we can find someone who is really familiar with the two repos to work on it.

###Option 2: Write a new search tool
I feel comfortable saying that the search gem is more complex than it needs to be, which has made it difficult to troubleshoot. @gemfarmer wrote a Jekyll-based search for EITI in Javascript that could be abstracted into a workable option:
- [Javascript search functionality](https://github.com/18F/doi-extractives-data/blob/dev/js/components/search.js)
- [Ruby data store creation](https://github.com/18F/doi-extractives-data/blob/dev/_plugins/search.rb)
- [HTML results page template](https://github.com/18F/doi-extractives-data/blob/dev/pages/search-results.html)

[It could also be done sans Ruby, though I'm not sure if that's a less scalable way to do it.](https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/)

###Option 3: Use an existing open-source Jekyll search plugin
Instead of maintaining our own tool, for which we will continually need to find maintenance hours, we could use someone else's plugin. Here are some options that I intend to test:
- (lunr.js-based option)[https://github.com/slashdotdash/jekyll-lunr-js-search] (requires jQuery)
- (vanilla JS + JSON option)[https://github.com/christian-fei/Simple-Jekyll-Search]

###Option 4: Use DigitalGov search instead
I think this would be a fine option, but it would probably require site owners setting up their own instances (and they can't do that until sites are migrated, since DigitalGov needs a URL to crawl). It would also require some additional styling in the style gem, since DigitalGov is based on Google Custom Search or Site Search; hard to tell which. (I am slightly concerned because Google has announced it will EOL Google Site Search in April 2018, but that gives us a year to figure something else out if need be.)

So using DigitalGov search would require the following efforts:
1. *Dev* - Remove the search gem dependency from the style gem
2. *Dev* - Replace & style the code for the search box in the style repo
3. *Dev* - Replace & style the template for the search results in the style repo
4. *Dev* - Write new logic to check for a search variable related to the individual site's DigitalGov search instance in the site's `_config.yml` file and render 2 & 3 if 4 is found
5. *Site owners* - Upgrade `guides_style_18f` gem
6. *Site owners* - Remove/replace any custom code (some repos appear to have custom `search.html` templates)
7. *Site owners* - Set up a DigitalGov search instance (we'd want to write up a how-to, as the UX is rather unintuitive)
8. *Site owners* - Add their DigitalGov search key/UID/whatever it is to their config.

**Comment by afeld** [comment]
> the jekyll_pages_api_search gem that is required by guides_style_18f is not compatible with versions of Jekyll greater than 3.1

https://github.com/18F/jekyll_pages_api_search/issues/37

> (lunr.js-based option)[https://github.com/slashdotdash/jekyll-lunr-js-search]

We proposed combining forces in https://github.com/slashdotdash/jekyll-lunr-js-search/issues/75, but never heard back.

**Comment by hbillings** [comment]
@afeld Yeah, I've read that issue half a dozen times hoping something in it would prompt an epiphany, heh. So far it's just made me sad.

**Comment by hbillings** [comment]
_Rolling update log_
- I tried [Simple Jekyll Search](https://github.com/christian-fei/Simple-Jekyll-Search). Maybe I need to build it locally or something, but the minified file provided uses `require` statements. Introducing Browserify or something similar just to handle search seems overly complex (though this is modern javascript, so everything is more complex than I think it should be). Conclusion: 👎 

I'll update this comment with further experiments as applicable.

**Comment by wslack** [comment]
👍

**Comment by wslack** [comment]
Met with Dawn from DigitalGov search; we should add more documentation on their offering.

**Comment by jseppi** [comment]
This seems to be the same issue as https://github.com/18F/federalist-docs/issues/85 from what I understand. Basically, adding a bit of documentation to `federalist-docs` that says the recommended method of adding search is to use DigitalGov Search.

**Comment by wslack** [comment]
https://github.com/18F/federalist-docs/issues/123 has the remaining todos

**Comment by afeld** [comment]
They are different, right? Being able to search https://federalist-docs.18f.gov/ vs. documentation about how Federalist sites can set up search.

**Comment by jseppi** [comment]
Yes, they are different, but we want to have the search setup on our docs and use that as an example to suss out the rest of the process for the digitalgov-search recommendation.

**Comment by wslack** [comment]
https://docs.google.com/document/d/1wG2tbJJ9u26nDRAlTnyvruTScTMHsGV5pykXzBHN_aU/edit# has other references. @jseppi did you open another issue for the rest of the work here?

**Comment by jseppi** [comment]
Yes: https://github.com/18F/federalist-docs/issues/123
