### ISSUE TITLE
ATO Work for Queue

### ISSUE THREAD

**Issue by wslack** [18F/federalist#398]
- [X]  Work with Noah and Diego on evaluating what is needed to properly leverage cloud.gov
- [ ] Work to micropurchase an SQS broker (not urgent)

**Comment by wslack** [comment]
Update: moving this to icebox given lack of SQS support at this time.

**Comment by wslack** [comment]
When we want a Federal Agency ATO, we'll need to get off of SQS. Options:

1. Redis
2. Rearchitect
3. cloud.gov team adds a SQS broker (but won't be in FedRAMP boundary)

**Comment by wslack** [comment]
If with Redis, will need code for redis as a queue

**Comment by brandocalrissian** [comment]
As I hadn't thought about using Redis as a queue before; searching found this: http://redis.io/commands/rpoplpush

Any signaling mechanism available on both sides of the producer/consumer divide that provides for guaranteed delivery and is valid for the ATO/FedRAMP considerations would be in play.

Redis would be easier as it's simple to spin up in cloud.gov. When what we have available is good enough, why add the effort to get another tool in the door?

Changing from a guaranteed queue to a different architecture should be done because it's better and necessary for the product. If the current architecture can work in our constraints, I say let's not rush to modify it.

**Comment by wslack** [comment]
Options:
1. Refactor for Redis
2. Infra pays for cloud.gov to set up an SQS (will take some time)
3. Put into E/W manually in legacy enterprise account. (via issues to infrastructure team)

**Comment by jseppi** [comment]
There hasn't been any movement on this in nearly a year. I don't really have visibility into what, if anything, needs to be done to resolve this. Or are we good to go?

**Comment by wslack** [comment]
This will be resolved when the F1.1 ATO is done.
