### ISSUE TITLE
Wireframe - Established User States

### ISSUE THREAD

**Issue by bradnunnally** [18F/federalist#40]
Here are two wireframes which I think represent the two states of Federalist of an established user that has created and been added to sites that exist in the system. . 

These wireframes are DRAFT, they have not been reviewed by any teammates or potential users. So everything is up for change. 

![federalist_wireframe_established_user](https://cloud.githubusercontent.com/assets/12515096/8114895/4e5fa5aa-103d-11e5-965f-e9c807f6ae73.png)
![federalist_wireframe_established_user_add](https://cloud.githubusercontent.com/assets/12515096/8114896/4e6310dc-103d-11e5-9764-c54556894fa5.png)

Things that needs to happen with them:
 - Validate with potential users and teammates
 - Visual design 
 - UI Development

**Comment by jeremiak** [comment]
Looks great. I'll be interested to see if things like the engine are actually valuable to show for the end user but I suppose we'll find that out shortly!

**Comment by jeremiak** [comment]
The add site view confuses me just a bit. I think we might want an even more abstract workflow:

1. Do you already have a repository/site on Github? If so add it here.
2. Oh you need to make a site from scratch? No problem, here are three templates you can choose from.

**Comment by bradnunnally** [comment]
Good call! I'll make some edits today based on the workflow you describe.

**Comment by dhcole** [comment]
>  I'll be interested to see if things like the engine are actually valuable to show for the end user 

I think we could test for the automatically by looking for

**Comment by dhcole** [comment]
Curious, why ask for number of users?

**Comment by bradnunnally** [comment]
@dhcole In the prototype that @jeremiak set up, I thought there was a field for number of users. I could have been mistaken though or read it incorrectly.

**Comment by bradnunnally** [comment]
@jeremiak Is it possible to pull in a person's repos from github in some sort of listing? I'm wondering if they are adding a site from an existing repo, rather than have them type in the repo name we show them a list of their owned repos to choose from. If we can do this, it's possible to remove a lot of human error from the workflow.

**Comment by jeremiak** [comment]
@bradnunnally I think there might have been that field but I think that was also just me putting fields on the page. It's going to be more useful when we get to phase two and it enables "admin"-like people to give permissions to other people they know.

Also, totally possible re: type-ahead and I think its an awesome idea! That would assuredly cut down on the user entered errors there but I think for the first few iterations of this things life we don't need it yet because I think lots of people who want to enter Github repos will know what that means... for now. Also, I would hypothesize that we want to really fine-tune the "create new site from scratch and from one of our templates" instead of "add your own repo" because the first option is going to incorporate lots of the best practices that 18F and other digital gov folks have developed. These are hopefully going to be things like analytics and editor configuration tools that should make their lives just a bit easier.

**Comment by bradnunnally** [comment]
@jeremiak Ah! That makes sense about the field. I'll kill it on the wireframe to avoid future confusion. 

Totally agree that the focus should be on new site from scratch or from a template. We can make a lot of wins by getting that out of the door first. This was a rabbit hole I was just wondering as I think through the process of things.

**Comment by bradnunnally** [comment]
I've updated the wireframe based on this feedback. Does it look like I've missed anything?
![federalist_wireframe_established_user_add](https://cloud.githubusercontent.com/assets/12515096/8185287/48af6064-1411-11e5-925d-4ade13dbde70.png)

**Comment by dhcole** [comment]
Great work @bradnunnally. Closing since this is captured here: https://github.com/18F/federalist/wiki/Design-Documentation
