### ISSUE TITLE
Set up a way to deploy onto a Federalist "staging server" instead of relying on local testing

### ISSUE THREAD

**Issue by wslack** [18F/federalist#405]

**Comment by jeremiak** [comment]
We want a staging environment for a number of reasons. The major one is so that we can smoke test different pushes before we release to our production environment.

The second is so that there is more documentation and knowledge across the team of how the various parts of the app work together to make Federalist go.

**Comment by jeremiak** [comment]
Part of this is doing a lot of the initial work/research for things like:

* ATO queue for storage work - #397 
* ATO work for queue - #398

**Comment by jeremiak** [comment]
I was able to get an S3 service set up with the service broker in the `staging` space within the `federalist` org on cloud.gov, but am currently waiting on some guidance about how to get a queue resource ([comment on 18f/infrastructure#625](https://github.com/18F/Infrastructure/issues/625#issuecomment-242091239))
