### ISSUE TITLE
Clarify how/if Federalist supports private repos

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#410]

**Comment by wslack** [comment]
Just needs a few words on docs site for searchers.

**Comment by eddietejeda** [comment]
The answer is yes, we support private repos.

@amirahaziz can you see where this could fit in the documentation page?

**Comment by amirahaziz** [comment]
I think we should add this on this page, under "basic settings": https://federalist.18f.gov/documentation/

The content should be a new bullet, probably under "Live site branch". The content should read:
Repository Settings: Federalist does support both public and private repo settings. You can still connect your current repos with Federalist and maintain limited viability. We just need you to share that repo with us so we'd like be able to access them. Otherwise, feel free to keep your repos public and/or private.

**Comment by amirbey** [comment]
@amirahaziz  to raise PR
