### ISSUE TITLE
Some files are not being pushed to S3

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#570]
This is an issue I've run into trying to debug the handbook's search functionality ([18F/handbook#63](https://github.com/18F/handbook/issues/63)).

I've tried to build [18f/handbook](/18f/handbook) but a few files are not being pushed to S3 while it seems like many others are. The following files are returning a 404 and are not present in S3:
- `/search/`
- `/search-index.json`
- `/search-index.json.gz`

However, many of the other files are there. I forked the [handbook](/jeremiak/handbook), added it to Federalist, and ran into the same problem.

I pulled down [`master` on 18f/federalist-docker-build](https://github.com/18F/federalist-docker-build/commit/e3050d260b2d545e870361275637dd500babce5b), ran the image with a valid token for 18f/handbook and I see that the missing files are, indeed, generated in the build process.

Any ideas?

**Comment by wslack** [comment]
https://federalist.18f.gov/preview/18f/handbook/awfrancisco-patch-1/search/?q=test still works, which tells me that builds were working three days ago. We should try pushing the handbook on GovCloud to see if the same issue is present.

**Comment by brownpl** [comment]
We are in the process of trying to push some preview branches for the scorecard and are also having some issues - not sure if they are related to this or if it is a separate issue. 

Our last successful build was about 9 days ago. Last night when I tried to push up a preview, the federalist log listed "Your Ruby version is 2.3.1, but your Gemfile specified 2.2.3". It seemed to timeout checking for the S3 files so the build failed. This morning, I had my colleague make a small tweak to the branch that previously built fine and he is also encountering the same error. 

I am unsure if any of the files are making it to the S3 bucket as I am not sure I have access to that information. (If there is a way for me to check, I'm happy to do so to help debug.)

**Comment by jmhooper** [comment]
@jeremiak and I did a lot of investigating here earlier and we discovered that this problem is a result of some jekyll plugins that silently fail when node is not available. The files that we thought weren't getting uploaded simply weren't building because those plugins could not reach out to node.

Some further investigation led us to discover that containers gave us this error:

```
ERR nvm is not compatible with the "PREFIX" environment variable: currently set to "site/jeremiak/handbook"
ERR Run `unset PREFIX` to unset it.
```

This occurred when we ran the builds in ECS and in cloud.gov, but not when we ran builds locally. Additionally, builds still worked when we fired up a build container locally and set the `PREFIX` environment variable in the shell.

I was eventually able to reproduce the error by starting a build container like this:

```
docker run -i -e "PREFIX=path/to/site" federalist-docker-build bash -l
```

So here we learned that the `PREFIX` variable has to be set when the container is started for the error to occur. This led me to check `~/.profile` where `nvm.sh` is invoked. Sure enough, invoking `nvm.sh` with `PREFIX` set results in the error.

The problem there is that `npm` actually uses the `PREFIX` env variable to resolve the path to things like its global config file. This was causing when initializing `nvm`.

It pulled together a quick fix for this here: https://github.com/18F/docker-ruby-ubuntu/pull/5

I think moving forward our best bet will be to merge that PR so builds will start working again in the short term.

In the long term we will probably want to change `PREFIX` to `SITE_PREFIX` in the main federalist app and federalist-docker-build and then revert the above change in docker-ruby-ubuntu.

**Comment by wslack** [comment]
Question for next week: what sort of "unit tests" can we do to catch these in staging in the future?

Also, how do we improve logging so that issues like these are more easily debugged?

**Comment by wslack** [comment]
I merged the PR and search still isn't working.

**Comment by jmhooper** [comment]
We may need need to trigger a rebuild for federalist-docker-build on docker hub and then rebuild the broken sites. I'll take a swing this afternoon.

**Comment by wslack** [comment]
All good now!

**Comment by jeremiak** [comment]
Awesome work, thanks @jmhooper!

**Comment by brownpl** [comment]
FWIW - worked great for me. Thank you!
