### ISSUE TITLE
Verify that CloudTrail is enabled for Federalist's S3 bucket

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#692]
CloudTrail will [enable us to log API calls to our S3 bucket](http://docs.aws.amazon.com/AmazonS3/latest/dev/cloudtrail-logging.html). This information will be necessary if we wish to audit changes made to the content in the S3 bucket.

I would assume that cloud.gov have CloudTrail enabled for its brokered S3 services, but we should verify this for our ATO.

**Comment by wslack** [comment]
I can confirm that cloudtrail is enabled, but we will have to [do some steps to set up logging](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-event-selectors-for-a-trail.html).

**Comment by wslack** [comment]
Contents of logs include IP addresses: http://docs.aws.amazon.com/lambda/latest/dg/eventsources.html#eventsources-s3-put

**Comment by wslack** [comment]
We should wait to do this until GSA IT or our AO says we need to.

**Comment by NoahKunin** [comment]
Before I can determine if we POAM this or not, I'm having trouble understanding from the Slack comments what is actually "on" by default. 

What I'm grok-ing is that [all *bucket* ops are logged ](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketOps.html), but [*object* ops](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectOps.html) (i.e. content) are not. Does that jive?

Presuming "yes", we're fine for the first ATO and then I have to subjectively determine how long to give this one, since I thought we were already capturing this, and this will likely increase logs significantly.

**Comment by wslack** [comment]
@NoahKunin should this be a meeting at some point in the next month?

**Comment by jseppi** [comment]
Is this still relevant @wslack? Given today's ATO update it sounds like this can probably be closed.

**Comment by wslack** [comment]
concur
