### ISSUE TITLE
Remove hugo from list of build engines

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#756]
We currently do not support sites that use Hugo, so we should remove it from the list of options for build options.

**Comment by wslack** [comment]
Verified and done!

**Comment by jeremyzilar** [comment]
Hello — 
As we move DigitalGov over to Federalist, we would like to formally request that the Federalist Team consider supporting HUGO as a build option.

We currently have around 1550 blog posts, 120 pages, 300 event pages, and a few hundred additional collection pages.

This week, our team met with one of the members of the HUGO team here in New York. His name is Bud Parr. It became increasingly clear that in order to move DigitalGov to Federalist, we are going to need the key component Hugo offers — speed.

The tradeoffs between Jekyll and Hugo are slim, and the community around HUGO appears to be growing. It is also nice to be able to reach out to people on the core team with questions, should we get stuck.
🤗
