### ISSUE TITLE
Set up multiple custom domains?

### ISSUE THREAD

**Issue by zachmargolis** [18F/federalist#809]
Request from the #federalist-support Slack the other day:

> me: Hi, do federalist pages support 2 custom domains? Ex I want to make sure everything works and serve a site at `preview.login.gov`, but then also enable `www.login.gov` to work as well and transition smoothly?
> 
> will: @margolis do you want the same repo serving both?

the goal is to have the same repo serving content at two different domains, so we can have one ready as a "beta" and change DNS and enable the other to roll it out, and minimize number of moving pieces

**Comment by wslack** [comment]
It's trivial to have two URLs pointed at the same source repo. The problem is that Federalist "builds" a live site to pull its assets from the live URL (effectively setting `baseurl` for only the "live" build), so one URL of the site will have an issue loading assets.

It does mean the transition can be seemless, by just switching the "live" URL in Federalist config, but I'm frankly unsure how to make a static site using one codebase that pulls from different assets depending on the URL used to visit. Is this a one time need or will you be wanting to roll out changes using the two different URLs over the long erm?

We could set up a site to pull its assets from www.login.gov and then point preview.login.gov at the same source path....I'm frankly not sure what will happen.

Another way to jury-rig this would be to use Federalist's staging environment (where we test changes before deploying to prod) to host the preview URL; however, that URL would not have the same security headers as `prod`.

**Comment by zachmargolis** [comment]
Would it be possible to build two different sites (so we can set two different custom domains) for the same repo?

**Comment by wslack** [comment]
Only with the last possibility I posted:
> use Federalist's staging environment (where we test changes before deploying to prod) to host the preview URL; however, that URL would not have the same security headers as prod.

Federalist's data schema doesn't allow us to build two different versions of the same site - the S3 urls are based on the owning org + repo name. You could make a fork and update it from the main copy regularly, but that's also a little funky.

Is the concern/desire to have working preview versions of the site? If so, why not just use a straight preview URL like: https://federalist.fr.cloud.gov/preview/18f/18f.gsa.gov/dev/

You retain the ability to do full testing previews....since site.baseurl will work on the live site if it works on the preview.

**Comment by wslack** [comment]
We figured out how to do this using preview branches; the only thing is that the repo has to have a Ruby plugin to put assets in the right place if building for certain preview branches. Also, every link needs a trailing slash. (because the baseuul requires that)
