### ISSUE TITLE
Builds not working on federalist-staging

### ISSUE THREAD

**Issue by wslack** [18F/federalist#816]
Webhooks for at least one slide are "landing" but Federalist isn't doing new builds.

**Comment by jmhooper** [comment]
After some investigation, it appears that this may not be a bug. This issue was noticed when a site was pushing a new branch, but not seeing builds for that branch. Upon further investigation, we discovered that the new branch did not contain any new commits. When there are not new commits, [Federalist does not create a new build](https://github.com/18F/federalist/blob/c78b62e7d764f3a0124cbc8e949cee2c6309cd71/api/controllers/webhook.js#L15).

**Comment by wslack** [comment]
We are ok with this behavior and will close the issue.
